version: 0.0 # 고정, CodeDeploy 버전
os: linux
files:
  - source: / # 루트 경로(/)를 지정하면 전체 파일을 칭함
    destination: /home/ubuntu/app/step2/zip/ # 여기로 이동
    overwrite: yes # 덮어씌우기

# deploy.sh 있을 경우
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
