server:
  port: 9999

spring:
  profiles:
    include:
      - oauth
      - db
  session:
    store-type: jdbc
#    jdbc:
#      initialize-schema: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false



# jpa
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb

