spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1054202051679-2o1egvg0vv3krmgp6oufqamr6o6tpl3f.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile

          naver:
            client-id: cgXxJn4eghYAmWj7g6G_
            client-secret: KcoughcSDo
            scope: name, email, profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9999/login/oauth2/code/naver # 코드를 받을 uri

          kakao:
            client-id: 495c3e1bf7729ed4c261621af9cc596b
            client-secret: AucVXTVHFsCtuitGByU5MSKUghcMnV7C
            scope: profile_nickname, account_email, profile_image # 동의 항목
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST # 카카오는 필수 파라미터를 POST로 요청해야 한다.
            redirect-uri: http://localhost:9999/login/oauth2/code/kakao # 코드를 받을 uri

        provider:
          # 스프링 OAuth2-client 라이브러리의 provider 에는 구글,페이스북,트위터가 속해있어 redirect-uri , authorization-grant-type 를 적어주지 않아도 자동으로 고정적으로 등록되어 있다.(적어줘도 된다.) ex) /login/oauth2/facebook, google 로 고정
          # 하지만 네이버나 카카오톡은 Provider 가 아니기 때문에 적어주어야된다. 원하는대로 uri 를 지정할수 있다, 고정되어 있지 않다.
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 네이버 로그인 창을 요청하는 uri
            token-uri: https://nid.naver.com/oauth2.0/token # 네이버로부터 토큰을 요청하는 uri
            user-info-uri: https://openapi.naver.com/v1/nid/me # 네이버로부터 프로필 주소를 요청하는 uri
            user-name-attribute: response # 회원 정보를 받을 key 값 설정(json 형태 -> {"response" : {...}})

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # 카카오 로그인 창을 요청하는 uri
            token-uri: https://kauth.kakao.com/oauth/token # 카카오로부터 토큰을 요청하는 uri
            user-info-uri: https://kapi.kakao.com/v2/user/me # 카카오로부터 프로필 주소를 요청하는 uri
            user-name-attribute: id # 회원 정보를 받을 key 값 설정(json 형태 -> {"id" : {...}})
